// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcsyZL8Ae055Zwi-piX1oo2gDvdWSqN60',
    appId: '1:271131085251:web:1d0a0b1fbe1ebe54ba9576',
    messagingSenderId: '271131085251',
    projectId: 'mimo-to',
    authDomain: 'mimo-to.firebaseapp.com',
    storageBucket: 'mimo-to.appspot.com',
    measurementId: 'G-D0WBTERGEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg_S7f4RIwhHVQIO4M6Pqe5CpESpvPVok',
    appId: '1:271131085251:android:e1440bdbdb9bce71ba9576',
    messagingSenderId: '271131085251',
    projectId: 'mimo-to',
    storageBucket: 'mimo-to.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBFr6eAIBu46qUwXfjQISpJQ-YlMQssSQ',
    appId: '1:271131085251:ios:661543f04bee66baba9576',
    messagingSenderId: '271131085251',
    projectId: 'mimo-to',
    storageBucket: 'mimo-to.appspot.com',
    iosBundleId: 'com.example.mimoTo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBFr6eAIBu46qUwXfjQISpJQ-YlMQssSQ',
    appId: '1:271131085251:ios:661543f04bee66baba9576',
    messagingSenderId: '271131085251',
    projectId: 'mimo-to',
    storageBucket: 'mimo-to.appspot.com',
    iosBundleId: 'com.example.mimoTo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcsyZL8Ae055Zwi-piX1oo2gDvdWSqN60',
    appId: '1:271131085251:web:a150714312987c1bba9576',
    messagingSenderId: '271131085251',
    projectId: 'mimo-to',
    authDomain: 'mimo-to.firebaseapp.com',
    storageBucket: 'mimo-to.appspot.com',
    measurementId: 'G-P7SV35QNQ1',
  );
}
